service: my-request-api-service
app: my-request
org: softstack

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stackName: my-request-api-service
  apiName: my-request-api-service
  profile: softstack
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: services/create.create
    events:
      - http:
          path: src
          method: post
          cors: true

  list:
    handler: services/list.list
    events:
      - http:
          path: src
          method: get
          cors: true

  get:
    handler: services/get.get
    events:
      - http:
          path: services/{id}
          method: get
          cors: true

  update:
    handler: services/update.update
    events:
      - http:
          path: services/{id}
          method: put
          cors: true

  delete:
    handler: services/delete.delete
    events:
      - http:
          path: services/{id}
          method: delete
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
