service: authentication

app: my-request
org: ssfdev

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stackName: ${self:app}-${self:service}-${self:provider.stage}
  apiName: ${self:app}-${self:service}-${self:provider.stage}
  profile: default
  stage: ${opt:stage, 'dev'}
  stackTags:
    PROJECT: ${self:app}
    STAGE: ${self:provider.stage}
  environment:
    PROD_USERPOOL_ID: us-west-2_2rPpXcag5
    DEV_USERPOOL_ID: us-west-2_7vXlPMZyi
    STAGE: ${self:provider.stage}

functions:
  endpoints:
    name: ${self:app}-${self:service}-${self:provider.stage}
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          # authorizer:
          #   name: cognito-pool-auth
          #   arn: arn:aws:cognito-idp:us-west-2:418615587574:userpool/us-west-2_cyimjlwtU
          # cors: # removed true
          #   origin: '*' # <-- Specify allowed origin
          #   headers: # <-- Specify allowed headers
          #     - Content-Type
          #     - X-Amz-Date
          #     - Authorization
          #     - X-Api-Key
          #     - X-Amz-Security-Token
          #     - X-Amz-User-Agent
    layers:
      - arn:aws:lambda:us-west-2:418615587574:layer:my-request-libraries:4
    role: arn:aws:iam::418615587574:role/my-request-cognito-idp

custom:
  apiEndpoint:
    Fn::Join:
      - ""
      - - "https://"
        - Ref: "ApiGatewayRestApi"
        - ".execute-api."
        - ${self:provider.region}.
        - Ref: "AWS::URLSuffix"
        - "/"
        - ${self:provider.stage}
        - "/"

outputs:
  URL: ${self:custom.apiEndpoint}
