service: adminAutoConfirm
app: my-request
# org: softstack

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stackName: ${self:app}-${self:service}-stack
  apiName: ${self:app}-${self:service}-api
  # profile: ${self:org}
  profile: default
  stage: dev

functions:
  endpoints:
    name: ${self:app}-${self:service}-lambda
    handler: src/index.handler
    role: arn:aws:iam::418615587574:role/events-dev-us-west-2-lambdaRole
