// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-west-2",
  "aws_cognito_identity_pool_id": "us-west-2:68ff65f5-9fd0-42c9-80e1-325e03d9c1e9",
  "aws_cognito_region": "us-west-2",
  "aws_user_pools_id": "us-west-2_cyimjlwtU",
  "aws_user_pools_web_client_id": "2vah6r61ekscqp62f0oari1spr",
  "oauth": {},
  "aws_content_delivery_bucket": "my-request-20200226122412-hostingbucket-dev",
  "aws_content_delivery_bucket_region": "us-west-2",
  "aws_content_delivery_url": "http://my-request-20200226122412-hostingbucket-dev.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
